"""
Enterprise AI Report.

Represents the complete output produced by the
AnalystGPT Enterprise AI Insight Engine.

Sprint 14 Remediation — AI Insights + Enterprise Reporting Reliability Remediation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


@dataclass(
    frozen=True,
    slots=True,
)
class AIReport:
    """
    Immutable AI report generated from the reporting layer.

    This object represents the complete business insight
    generated by the configured Large Language Model.
    """

    # ==========================================================
    # Generated Content
    # ==========================================================

    executive_summary: str

    recommendations: list[str]

    explanations: list[str]

    narrative: str

    # ==========================================================
    # Model Information
    # ==========================================================

    model: str

    provider: str

    # ==========================================================
    # Execution Metadata
    # ==========================================================

    execution_time: float

    prompt_count: int = 1

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    # ==========================================================
    # Structured Enterprise Sections
    # ==========================================================

    key_findings: list[str] = field(default_factory=list)

    business_implications: list[str] = field(default_factory=list)

    risks: list[str] = field(default_factory=list)

    opportunities: list[str] = field(default_factory=list)

    actions: list[str] = field(default_factory=list)

    limitations: list[str] = field(default_factory=list)

    confidence: str = "High (Grounded in Deterministic Analytics)"

    # ==========================================================
    # Optional Metadata
    # ==========================================================

    metadata: dict[str, Any] = field(
        default_factory=dict,
    )

    # ==========================================================
    # Serialization
    # ==========================================================

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the AI report into a serialisable dictionary.
        """
        return {
            "executive_summary": self.executive_summary,
            "recommendations": self.recommendations,
            "explanations": self.explanations,
            "narrative": self.narrative,
            "key_findings": self.key_findings,
            "business_implications": self.business_implications,
            "risks": self.risks,
            "opportunities": self.opportunities,
            "actions": self.actions,
            "limitations": self.limitations,
            "confidence": self.confidence,
            "model": self.model,
            "provider": self.provider,
            "execution_time": self.execution_time,
            "prompt_count": self.prompt_count,
            "generated_at": (
                self.generated_at.isoformat()
                if isinstance(self.generated_at, datetime)
                else str(self.generated_at)
            ),
            "metadata": self.metadata,
        }
