"""
Enterprise AI Report.

Represents the complete output produced by the
AnalystGPT Enterprise AI Insight Engine.
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import UTC
from datetime import datetime
from typing import Any


@dataclass(
    frozen=True,
    slots=True,
)
class AIReport:
    """
    Immutable AI report generated from the reporting layer.

    This object represents the complete business insight
    generated by the configured Large Language Model.
    """

    # ==========================================================
    # Generated Content
    # ==========================================================

    executive_summary: str

    recommendations: list[str]

    explanations: list[str]

    narrative: str

    # ==========================================================
    # Model Information
    # ==========================================================

    model: str

    provider: str

    # ==========================================================
    # Execution Metadata
    # ==========================================================

    execution_time: float

    prompt_count: int

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(
            UTC,
        )
    )

    # ==========================================================
    # Optional Metadata
    # ==========================================================

    metadata: dict[str, Any] = field(
        default_factory=dict,
    )

    # ==========================================================
    # Serialization
    # ==========================================================

    def to_dict(
        self,
    ) -> dict[str, Any]:
        """
        Convert the AI report into a serialisable dictionary.
        """

        return {
            "executive_summary": self.executive_summary,
            "recommendations": self.recommendations,
            "explanations": self.explanations,
            "narrative": self.narrative,
            "model": self.model,
            "provider": self.provider,
            "execution_time": self.execution_time,
            "prompt_count": self.prompt_count,
            "generated_at": self.generated_at.isoformat(),
            "metadata": self.metadata,
        }