"""
Analytics Report Module

Generates the final analytics report by combining the results
from all analytics modules.
"""

from src.core.logger import logger


class AnalyticsReport:
    """
    Generates the enterprise analytics report.
    """

    def generate(self, results: dict) -> dict:
        """
        Assemble the final analytics report.

        Parameters
        ----------
        results : dict
            Results generated by all analytics modules.

        Returns
        -------
        dict
            Consolidated analytics report.
        """

        logger.info("Generating analytics report.")

        report = {
            "descriptive_statistics": results.get(
                "descriptive_statistics",
                {},
            ),
            "numerical_analysis": results.get(
                "numerical_analysis",
                {},
            ),
            "categorical_analysis": results.get(
                "categorical_analysis",
                {},
            ),
            "correlation_analysis": results.get(
                "correlation_analysis",
                {},
            ),
            "distribution_analysis": results.get(
                "distribution_analysis",
                {},
            ),
        }

        logger.info("Analytics report generated successfully.")

        return report