"""
Executive Summary Module

Generates a high-level business summary from the analytics report.
"""

from src.core.logger import logger


class ExecutiveSummary:
    """
    Generates executive-level summary statements.
    """

    def generate_summary(
        self,
        analytics_report: dict,
    ) -> list[str]:
        """
        Generate a concise executive summary from the analytics report.

        Args:
            analytics_report: Analytics report generated by the
                Analytics Module.

        Returns:
            List of executive summary statements.
        """

        logger.info("Generating executive summary.")

        summary = []

        section_count = len(analytics_report)

        summary.append(
            f"The analytics pipeline completed successfully with "
            f"{section_count} analytical sections."
        )

        if "descriptive_statistics" in analytics_report:
            summary.append(
                "Descriptive statistics were generated for the dataset."
            )

        if "numerical_analysis" in analytics_report:
            summary.append(
                "Numerical variables were analyzed for statistical insights."
            )

        if "categorical_analysis" in analytics_report:
            summary.append(
                "Categorical variables were analyzed for value distributions."
            )

        if "correlation_analysis" in analytics_report:
            summary.append(
                "Correlation analysis was completed to identify relationships between numerical variables."
            )

        if "distribution_analysis" in analytics_report:
            summary.append(
                "Distribution analysis was completed to understand data patterns."
            )

        summary.append(
            "Refer to the KPI section and detailed analytics for additional business insights."
        )

        logger.info("Executive summary generated successfully.")

        return summary