"""
KPI Formatter Module

Extracts key performance indicators from the analytics report.
"""

from typing import Any

from src.core.logger import logger


class KPIFormatter:
    """
    Formats business KPIs for reporting.
    """

    def format_kpis(
        self,
        analytics_report: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Extract business KPIs from the analytics report.

        Args:
            analytics_report: Analytics report generated by the
                Analytics Module.

        Returns:
            Dictionary containing reporting KPIs.
        """

        logger.info("Formatting KPI section.")

        kpis = {
            "Analytics Sections": len(analytics_report),
            "Descriptive Statistics": (
                "Available"
                if "descriptive_statistics" in analytics_report
                else "Unavailable"
            ),
            "Numerical Analysis": (
                "Available"
                if "numerical_analysis" in analytics_report
                else "Unavailable"
            ),
            "Categorical Analysis": (
                "Available"
                if "categorical_analysis" in analytics_report
                else "Unavailable"
            ),
            "Correlation Analysis": (
                "Available"
                if "correlation_analysis" in analytics_report
                else "Unavailable"
            ),
            "Distribution Analysis": (
                "Available"
                if "distribution_analysis" in analytics_report
                else "Unavailable"
            ),
        }

        logger.info("KPI section formatted successfully.")

        return kpis