"""
Reporting Manager Module

Coordinates the execution of the reporting pipeline and provides
format-specific report exporters.
"""

from __future__ import annotations

from pathlib import Path
import time
from typing import Any

from src.analytics.analytics_report import AnalyticsReport
from src.core.constants import REPORT_TITLE
from src.core.logger import logger
from src.reporting.executive_summary import ExecutiveSummary
from src.reporting.exporters.pdf_report_exporter import (
    PdfReportExporter,
)
from src.reporting.exporters.text_report_exporter import (
    TextReportExporter,
)
from src.reporting.kpi_formatter import KPIFormatter
from src.reporting.report_builder import ReportBuilder
from src.reporting.reporting_report import ReportingReport
from src.reporting.structured_report import StructuredReport


class ReportingManager:
    """
    Coordinates the execution of the reporting pipeline.
    """

    def __init__(self) -> None:
        """
        Initialise the reporting pipeline.
        """

        self.executive_summary = ExecutiveSummary()

        self.kpi_formatter = KPIFormatter()

        self.report_builder = ReportBuilder()

        self.text_report_exporter = (
            TextReportExporter()
        )

        self.pdf_report_exporter = (
            PdfReportExporter()
        )

    # ==========================================================
    # Public API
    # ==========================================================

    def generate_report(
        self,
        analytics_report: AnalyticsReport,
        output_path: str | Path | None = None,
    ) -> ReportingReport:
        """
        Execute the complete reporting pipeline.

        Parameters
        ----------
        analytics_report:
            Analytics report generated by the
            Analytics Module.
        output_path:
            Optional custom destination file path.

        Returns
        -------
        ReportingReport
            Final reporting result.
        """

        start_time = time.perf_counter()

        logger.info(
            "Starting reporting pipeline."
        )

        executive_summary = (
            self._generate_summary(
                analytics_report,
            )
        )

        kpis = self._format_kpis(
            analytics_report,
        )

        recommendations = (
            self._default_recommendations()
        )

        structured_report = (
            self._build_report(
                analytics_report=analytics_report,
                executive_summary=executive_summary,
                kpis=kpis,
                recommendations=recommendations,
            )
        )

        export_path = self._export_report(
            structured_report,
            output_path=output_path,
        )

        elapsed_time = (
            time.perf_counter()
            - start_time
        )

        logger.info(
            (
                "Reporting pipeline completed "
                "successfully in %.4f seconds."
            ),
            elapsed_time,
        )

        return ReportingReport(
            report=structured_report,
            export_path=export_path,
            execution_time=elapsed_time,
        )

    def export_text(
        self,
        report: StructuredReport,
        output_path: str | Path | None = None,
        ai_report: Any | None = None,
        lineage: dict[str, Any] | None = None,
    ) -> str:
        """
        Export a StructuredReport as a text file.
        """
        return self.text_report_exporter.export(
            report=report,
            output_path=output_path,
            ai_report=ai_report,
            lineage=lineage,
        )

    def export_pdf(
        self,
        report: StructuredReport,
        output_path: str | Path | None = None,
        ai_report: Any | None = None,
        lineage: dict[str, Any] | None = None,
    ) -> str:
        """
        Export a StructuredReport as a PDF file.
        """
        return self.pdf_report_exporter.export(
            report=report,
            output_path=output_path,
            ai_report=ai_report,
            lineage=lineage,
        )

    # ==========================================================
    # Internal Helpers
    # ==========================================================

    def _generate_summary(
        self,
        analytics_report: AnalyticsReport,
    ) -> str:
        """
        Generate the executive summary.
        """

        logger.info(
            "Generating executive summary..."
        )

        return (
            self.executive_summary.generate_summary(
                analytics_report.report,
            )
        )

    def _format_kpis(
        self,
        analytics_report: AnalyticsReport,
    ):
        """
        Generate formatted KPI section.
        """

        logger.info(
            "Formatting KPI section..."
        )

        return (
            self.kpi_formatter.format_kpis(
                analytics_report.report,
            )
        )

    def _default_recommendations(
        self,
    ) -> list[str]:
        """
        Return the default business recommendations.
        """

        return [
            (
                "Review the analytics findings "
                "before making business decisions."
            ),
            (
                "Validate business insights with "
                "domain experts when appropriate."
            ),
        ]

    def _build_report(
        self,
        analytics_report: AnalyticsReport,
        executive_summary: str,
        kpis,
        recommendations: list[str],
    ) -> StructuredReport:
        """
        Build the structured report.
        """

        logger.info(
            "Building structured report..."
        )

        return (
            self.report_builder.build_report(
                title=REPORT_TITLE,
                executive_summary=executive_summary,
                kpis=kpis,
                analytics=analytics_report.report,
                recommendations=recommendations,
            )
        )

    def _export_report(
        self,
        structured_report: StructuredReport,
        output_path: str | Path | None = None,
    ) -> str:
        """
        Export the default text report.
        """

        logger.info(
            "Exporting text report..."
        )

        path = self.text_report_exporter.export(
            structured_report,
            output_path=output_path,
        )

        if output_path is not None:
            try:
                latest_p = Path("reports/analystgpt_report.txt")
                latest_p.parent.mkdir(parents=True, exist_ok=True)
                latest_p.write_text(Path(path).read_text(encoding="utf-8"), encoding="utf-8")
            except Exception:
                pass

        return path
