"""
Reporting Manager Module

Coordinates the execution of the reporting pipeline.
"""

import time

from src.core.constants import REPORT_TITLE
from src.core.logger import logger
from src.reporting.executive_summary import ExecutiveSummary
from src.reporting.exporters.text_report_exporter import (
    TextReportExporter,
)
from src.reporting.kpi_formatter import KPIFormatter
from src.reporting.report_builder import ReportBuilder
from src.reporting.reporting_report import ReportingReport


class ReportingManager:
    """
    Coordinates the execution of the reporting pipeline.
    """

    def __init__(self) -> None:
        """
        Initialize the reporting pipeline.
        """

        self.executive_summary = ExecutiveSummary()
        self.kpi_formatter = KPIFormatter()
        self.report_builder = ReportBuilder()
        self.text_report_exporter = TextReportExporter()

    def generate_report(self, analytics_report: dict) -> dict:
        """
        Execute the complete reporting pipeline.

        Args:
            analytics_report: Analytics results generated by the
                Analytics Module.

        Returns:
            Dictionary representation of the completed reporting result.
        """

        start_time = time.perf_counter()

        logger.info("Starting reporting pipeline.")

        logger.info("Generating executive summary...")
        executive_summary = self.executive_summary.generate_summary(
            analytics_report
        )

        logger.info("Formatting KPI section...")
        kpis = self.kpi_formatter.format_kpis(
            analytics_report
        )

        recommendations = [
            "Review the analytics findings before making business decisions.",
            "Validate business insights with domain experts when appropriate.",
        ]

        logger.info("Building structured report...")
        structured_report = self.report_builder.build_report(
            title=REPORT_TITLE,
            executive_summary=executive_summary,
            kpis=kpis,
            analytics=analytics_report,
            recommendations=recommendations,
        )

        logger.info("Exporting text report...")
        export_path = self.text_report_exporter.export(
            structured_report
        )

        elapsed_time = time.perf_counter() - start_time

        logger.info(
            f"Reporting pipeline completed successfully in "
            f"{elapsed_time:.4f} seconds."
        )

        reporting_report = ReportingReport(
            report=structured_report,
            export_path=export_path,
            execution_time=elapsed_time,
        )

        return reporting_report.to_dict()