"""
Reporting Manager Module

Coordinates the execution of the reporting pipeline.
"""

import time

from src.analytics.analytics_report import AnalyticsReport
from src.core.constants import REPORT_TITLE
from src.core.logger import logger
from src.reporting.executive_summary import ExecutiveSummary
from src.reporting.exporters.text_report_exporter import (
    TextReportExporter,
)
from src.reporting.kpi_formatter import KPIFormatter
from src.reporting.report_builder import ReportBuilder
from src.reporting.reporting_report import ReportingReport


class ReportingManager:
    """
    Coordinates the execution of the reporting pipeline.
    """

    def __init__(self) -> None:
        """
        Initialize the reporting pipeline.
        """

        self.executive_summary = ExecutiveSummary()
        self.kpi_formatter = KPIFormatter()
        self.report_builder = ReportBuilder()
        self.text_report_exporter = TextReportExporter()

    def generate_report(
        self,
        analytics_report: AnalyticsReport,
    ) -> ReportingReport:
        """
        Execute the complete reporting pipeline.

        Parameters
        ----------
        analytics_report:
            Analytics report generated by the Analytics Module.

        Returns
        -------
        ReportingReport
            Final reporting result.
        """

        start_time = time.perf_counter()

        logger.info("Starting reporting pipeline.")

        logger.info("Generating executive summary...")
        executive_summary = (
            self.executive_summary.generate_summary(
                analytics_report.report
            )
        )

        logger.info("Formatting KPI section...")
        kpis = self.kpi_formatter.format_kpis(
            analytics_report.report
        )

        recommendations = [
            "Review the analytics findings before making business decisions.",
            "Validate business insights with domain experts when appropriate.",
        ]

        logger.info("Building structured report...")

        structured_report = self.report_builder.build_report(
            title=REPORT_TITLE,
            executive_summary=executive_summary,
            kpis=kpis,
            analytics=analytics_report.report,
            recommendations=recommendations,
        )

        logger.info("Exporting text report...")

        export_path = self.text_report_exporter.export(
            structured_report
        )

        elapsed_time = time.perf_counter() - start_time

        logger.info(
            "Reporting pipeline completed successfully in %.4f seconds.",
            elapsed_time,
        )

        return ReportingReport(
            report=structured_report,
            export_path=export_path,
            execution_time=elapsed_time,
        )