"""
Structured Report.

Canonical business report produced by the Reporting Module.

This object is consumed by the AI Insight Engine,
REST API, Power BI integration, Streamlit frontend,
and future React frontend.
"""

from __future__ import annotations

import json

from dataclasses import dataclass
from dataclasses import field
from datetime import UTC
from datetime import datetime
from typing import Any


@dataclass(
    frozen=True,
    slots=True,
)
class StructuredReport:
    """
    Immutable structured business report.

    This is the canonical business document generated by the
    Reporting Module and shared across the application.
    """

    # ==========================================================
    # Report Metadata
    # ==========================================================

    title: str

    executive_summary: str

    # ==========================================================
    # Business Content
    # ==========================================================

    kpis: dict[str, Any]

    analytics: dict[str, Any]

    recommendations: list[str]

    # ==========================================================
    # Metadata
    # ==========================================================

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(
            UTC,
        )
    )

    metadata: dict[str, Any] = field(
        default_factory=dict,
    )

    # ==========================================================
    # Convenience Properties
    # ==========================================================

    @property
    def has_kpis(
        self,
    ) -> bool:
        """
        Return True when KPI information exists.
        """

        return bool(
            self.kpis,
        )

    @property
    def has_analytics(
        self,
    ) -> bool:
        """
        Return True when analytics are available.
        """

        return bool(
            self.analytics,
        )

    @property
    def has_recommendations(
        self,
    ) -> bool:
        """
        Return True when recommendations exist.
        """

        return bool(
            self.recommendations,
        )

    # ==========================================================
    # Serialization
    # ==========================================================

    def to_dict(
        self,
    ) -> dict[str, Any]:
        """
        Convert the structured report into a serialisable
        dictionary.
        """

        return {
            "title": self.title,
            "executive_summary": self.executive_summary,
            "kpis": self.kpis,
            "analytics": self.analytics,
            "recommendations": self.recommendations,
            "generated_at": (
                self.generated_at.isoformat()
            ),
            "metadata": self.metadata,
        }

    def to_json(
        self,
        *,
        indent: int = 2,
    ) -> str:
        """
        Convert the report into formatted JSON.
        """

        return json.dumps(
            self.to_dict(),
            indent=indent,
            default=str,
        )

    # ==========================================================
    # Representation
    # ==========================================================

    def __repr__(
        self,
    ) -> str:

        return (
            "StructuredReport("
            f"title={self.title!r}, "
            f"kpis={len(self.kpis)}, "
            f"analytics={len(self.analytics)}, "
            f"recommendations={len(self.recommendations)}"
            ")"
        )